//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("SASModel", "FK_Inst_Depto", "Institucion", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.One, typeof(MemotraficoV2.Models.Institucion), "Departamento", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MemotraficoV2.Models.Departamento), true)]

#endregion

namespace MemotraficoV2.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class SASEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto SASEntities usando la cadena de conexión encontrada en la sección 'SASEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public SASEntities() : base("name=SASEntities", "SASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SASEntities.
        /// </summary>
        public SASEntities(string connectionString) : base(connectionString, "SASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto SASEntities.
        /// </summary>
        public SASEntities(EntityConnection connection) : base(connection, "SASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Departamento> Departamento
        {
            get
            {
                if ((_Departamento == null))
                {
                    _Departamento = base.CreateObjectSet<Departamento>("Departamento");
                }
                return _Departamento;
            }
        }
        private ObjectSet<Departamento> _Departamento;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Email> Email
        {
            get
            {
                if ((_Email == null))
                {
                    _Email = base.CreateObjectSet<Email>("Email");
                }
                return _Email;
            }
        }
        private ObjectSet<Email> _Email;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Institucion> Institucion
        {
            get
            {
                if ((_Institucion == null))
                {
                    _Institucion = base.CreateObjectSet<Institucion>("Institucion");
                }
                return _Institucion;
            }
        }
        private ObjectSet<Institucion> _Institucion;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Departamento. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDepartamento(Departamento departamento)
        {
            base.AddObject("Departamento", departamento);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Email. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmail(Email email)
        {
            base.AddObject("Email", email);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Institucion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToInstitucion(Institucion institucion)
        {
            base.AddObject("Institucion", institucion);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SASModel", Name="Departamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Departamento : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Departamento.
        /// </summary>
        /// <param name="idDepartamento">Valor inicial de la propiedad IdDepartamento.</param>
        /// <param name="idInstitucionFk">Valor inicial de la propiedad IdInstitucionFk.</param>
        public static Departamento CreateDepartamento(global::System.Int32 idDepartamento, global::System.Int32 idInstitucionFk)
        {
            Departamento departamento = new Departamento();
            departamento.IdDepartamento = idDepartamento;
            departamento.IdInstitucionFk = idInstitucionFk;
            return departamento;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDepartamento
        {
            get
            {
                return _IdDepartamento;
            }
            set
            {
                if (_IdDepartamento != value)
                {
                    OnIdDepartamentoChanging(value);
                    ReportPropertyChanging("IdDepartamento");
                    _IdDepartamento = StructuralObject.SetValidValue(value, "IdDepartamento");
                    ReportPropertyChanged("IdDepartamento");
                    OnIdDepartamentoChanged();
                }
            }
        }
        private global::System.Int32 _IdDepartamento;
        partial void OnIdDepartamentoChanging(global::System.Int32 value);
        partial void OnIdDepartamentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titular
        {
            get
            {
                return _Titular;
            }
            set
            {
                OnTitularChanging(value);
                ReportPropertyChanging("Titular");
                _Titular = StructuralObject.SetValidValue(value, true, "Titular");
                ReportPropertyChanged("Titular");
                OnTitularChanged();
            }
        }
        private global::System.String _Titular;
        partial void OnTitularChanging(global::System.String value);
        partial void OnTitularChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ext
        {
            get
            {
                return _Ext;
            }
            set
            {
                OnExtChanging(value);
                ReportPropertyChanging("Ext");
                _Ext = StructuralObject.SetValidValue(value, true, "Ext");
                ReportPropertyChanged("Ext");
                OnExtChanged();
            }
        }
        private global::System.String _Ext;
        partial void OnExtChanging(global::System.String value);
        partial void OnExtChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdInstitucionFk
        {
            get
            {
                return _IdInstitucionFk;
            }
            set
            {
                OnIdInstitucionFkChanging(value);
                ReportPropertyChanging("IdInstitucionFk");
                _IdInstitucionFk = StructuralObject.SetValidValue(value, "IdInstitucionFk");
                ReportPropertyChanged("IdInstitucionFk");
                OnIdInstitucionFkChanged();
            }
        }
        private global::System.Int32 _IdInstitucionFk;
        partial void OnIdInstitucionFkChanging(global::System.Int32 value);
        partial void OnIdInstitucionFkChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SASModel", "FK_Inst_Depto", "Institucion")]
        public Institucion Institucion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Institucion>("SASModel.FK_Inst_Depto", "Institucion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Institucion>("SASModel.FK_Inst_Depto", "Institucion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Institucion> InstitucionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Institucion>("SASModel.FK_Inst_Depto", "Institucion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Institucion>("SASModel.FK_Inst_Depto", "Institucion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SASModel", Name="Email")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Email : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Email.
        /// </summary>
        /// <param name="idEmail">Valor inicial de la propiedad IdEmail.</param>
        /// <param name="emailTo">Valor inicial de la propiedad EmailTo.</param>
        /// <param name="subject">Valor inicial de la propiedad Subject.</param>
        /// <param name="message">Valor inicial de la propiedad Message.</param>
        /// <param name="idUser">Valor inicial de la propiedad IdUser.</param>
        /// <param name="status">Valor inicial de la propiedad Status.</param>
        /// <param name="tipoEmail">Valor inicial de la propiedad TipoEmail.</param>
        public static Email CreateEmail(global::System.Int32 idEmail, global::System.String emailTo, global::System.String subject, global::System.String message, global::System.String idUser, global::System.String status, global::System.String tipoEmail)
        {
            Email email = new Email();
            email.IdEmail = idEmail;
            email.EmailTo = emailTo;
            email.Subject = subject;
            email.Message = message;
            email.IdUser = idUser;
            email.Status = status;
            email.TipoEmail = tipoEmail;
            return email;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEmail
        {
            get
            {
                return _IdEmail;
            }
            set
            {
                if (_IdEmail != value)
                {
                    OnIdEmailChanging(value);
                    ReportPropertyChanging("IdEmail");
                    _IdEmail = StructuralObject.SetValidValue(value, "IdEmail");
                    ReportPropertyChanged("IdEmail");
                    OnIdEmailChanged();
                }
            }
        }
        private global::System.Int32 _IdEmail;
        partial void OnIdEmailChanging(global::System.Int32 value);
        partial void OnIdEmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailTo
        {
            get
            {
                return _EmailTo;
            }
            set
            {
                OnEmailToChanging(value);
                ReportPropertyChanging("EmailTo");
                _EmailTo = StructuralObject.SetValidValue(value, false, "EmailTo");
                ReportPropertyChanged("EmailTo");
                OnEmailToChanged();
            }
        }
        private global::System.String _EmailTo;
        partial void OnEmailToChanging(global::System.String value);
        partial void OnEmailToChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false, "Subject");
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false, "Message");
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                OnIdUserChanging(value);
                ReportPropertyChanging("IdUser");
                _IdUser = StructuralObject.SetValidValue(value, false, "IdUser");
                ReportPropertyChanged("IdUser");
                OnIdUserChanged();
            }
        }
        private global::System.String _IdUser;
        partial void OnIdUserChanging(global::System.String value);
        partial void OnIdUserChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoEmail
        {
            get
            {
                return _TipoEmail;
            }
            set
            {
                OnTipoEmailChanging(value);
                ReportPropertyChanging("TipoEmail");
                _TipoEmail = StructuralObject.SetValidValue(value, false, "TipoEmail");
                ReportPropertyChanged("TipoEmail");
                OnTipoEmailChanged();
            }
        }
        private global::System.String _TipoEmail;
        partial void OnTipoEmailChanging(global::System.String value);
        partial void OnTipoEmailChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SASModel", Name="Institucion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Institucion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Institucion.
        /// </summary>
        /// <param name="idInstitucion">Valor inicial de la propiedad IdInstitucion.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        public static Institucion CreateInstitucion(global::System.Int32 idInstitucion, global::System.String nombre)
        {
            Institucion institucion = new Institucion();
            institucion.IdInstitucion = idInstitucion;
            institucion.Nombre = nombre;
            return institucion;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdInstitucion
        {
            get
            {
                return _IdInstitucion;
            }
            set
            {
                if (_IdInstitucion != value)
                {
                    OnIdInstitucionChanging(value);
                    ReportPropertyChanging("IdInstitucion");
                    _IdInstitucion = StructuralObject.SetValidValue(value, "IdInstitucion");
                    ReportPropertyChanged("IdInstitucion");
                    OnIdInstitucionChanged();
                }
            }
        }
        private global::System.Int32 _IdInstitucion;
        partial void OnIdInstitucionChanging(global::System.Int32 value);
        partial void OnIdInstitucionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Siglas
        {
            get
            {
                return _Siglas;
            }
            set
            {
                OnSiglasChanging(value);
                ReportPropertyChanging("Siglas");
                _Siglas = StructuralObject.SetValidValue(value, true, "Siglas");
                ReportPropertyChanged("Siglas");
                OnSiglasChanged();
            }
        }
        private global::System.String _Siglas;
        partial void OnSiglasChanging(global::System.String value);
        partial void OnSiglasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titular
        {
            get
            {
                return _Titular;
            }
            set
            {
                OnTitularChanging(value);
                ReportPropertyChanging("Titular");
                _Titular = StructuralObject.SetValidValue(value, true, "Titular");
                ReportPropertyChanged("Titular");
                OnTitularChanged();
            }
        }
        private global::System.String _Titular;
        partial void OnTitularChanging(global::System.String value);
        partial void OnTitularChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true, "Telefono");
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ext
        {
            get
            {
                return _Ext;
            }
            set
            {
                OnExtChanging(value);
                ReportPropertyChanging("Ext");
                _Ext = StructuralObject.SetValidValue(value, true, "Ext");
                ReportPropertyChanged("Ext");
                OnExtChanged();
            }
        }
        private global::System.String _Ext;
        partial void OnExtChanging(global::System.String value);
        partial void OnExtChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SASModel", "FK_Inst_Depto", "Departamento")]
        public EntityCollection<Departamento> Departamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Departamento>("SASModel.FK_Inst_Depto", "Departamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Departamento>("SASModel.FK_Inst_Depto", "Departamento", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
